#!/usr/bin/env bash
set -euo pipefail

PROFILE="/var/lib/n0jcg-winlink-webmail/radio-profile.conf"
[[ "${EUID:-$(id -u)}" == "0" ]] || { echo "FAIL: root is required" >&2; exit 1; }
[[ -f "$PROFILE" ]] || { echo "FAIL: radio profile is not configured" >&2; exit 1; }
# shellcheck disable=SC1090
source "$PROFILE"
[[ "${N0JCG_PACKET_CALLSIGN:-}" =~ ^[A-Z0-9-]{3,15}$ ]] || { echo "FAIL: invalid packet callsign" >&2; exit 1; }
[[ -z "${N0JCG_AUDIO_DEVICE:-}" || "${N0JCG_AUDIO_DEVICE:-}" =~ ^(plughw|hw):([A-Za-z0-9_=]+),[0-9]+$ ]] || { echo "FAIL: invalid audio device" >&2; exit 1; }
[[ -e "${N0JCG_PTT_DEVICE:-}" ]] || { echo "FAIL: PTT device not found" >&2; exit 1; }
CONFIG_DIR="/etc/n0jcg-winlink"
CONFIG_READY=0
for attempt in 1 2 3; do
    # Keep directory creation and permission update separate. Some minimal
    # install implementations report a misleading chmod/EROFS failure when
    # install -d touches an existing directory during a transient remount.
    if mkdir -p "$CONFIG_DIR" && chmod 0755 "$CONFIG_DIR"; then
        CONFIG_READY=1
        break
    fi
    mount -o remount,rw / >/dev/null 2>&1 || true
    sleep 1
done
if [[ "$CONFIG_READY" != "1" ]]; then
    echo "FAIL: /etc/n0jcg-winlink is not writable; the Pi filesystem may be read-only" >&2
    exit 30
fi
cat > /etc/n0jcg-winlink/direwolf.conf <<EOF
# Generated by N0JCG Winlink Email Server operator controls
# n0jcg-direwolf.service opens ALSA and forwards the metered PCM stream.
ADEVICE stdin
CHANNEL 0
MYCALL ${N0JCG_PACKET_CALLSIGN}
MODEM 1200
PTT ${N0JCG_PTT_DEVICE} RTS
AGWPORT 8000
KISSPORT 8001
EOF
install -m 0644 "$PROFILE" /etc/n0jcg-winlink/radio-profile.conf
systemctl enable --now n0jcg-direwolf.service
echo "PASS: packet station profile applied for ${N0JCG_PACKET_CALLSIGN}"
