#!/usr/bin/env bash
set -euo pipefail

PROFILE="/var/lib/n0jcg-winlink-webmail/radio-profile.conf"
[[ "${EUID:-$(id -u)}" == "0" ]] || { echo "FAIL: root is required" >&2; exit 1; }
[[ -f "$PROFILE" ]] || { echo "FAIL: radio profile is not configured" >&2; exit 1; }
# shellcheck disable=SC1090
source "$PROFILE"
[[ "${N0JCG_PACKET_CALLSIGN:-}" =~ ^[A-Z0-9-]{3,15}$ ]] || { echo "FAIL: invalid packet callsign" >&2; exit 1; }
[[ "${N0JCG_AUDIO_DEVICE:-}" =~ ^(plughw|hw):[0-9]+,[0-9]+$ ]] || { echo "FAIL: invalid audio device" >&2; exit 1; }
[[ -e "${N0JCG_PTT_DEVICE:-}" ]] || { echo "FAIL: PTT device not found" >&2; exit 1; }
install -d -m 0755 /etc/n0jcg-winlink
cat > /etc/n0jcg-winlink/direwolf.conf <<EOF
# Generated by N0JCG Winlink Email Server operator controls
ADEVICE ${N0JCG_AUDIO_DEVICE}
CHANNEL 0
MYCALL ${N0JCG_PACKET_CALLSIGN}
MODEM 1200
PTT CM108 ${N0JCG_PTT_DEVICE}
AGWPORT 8000
KISSPORT 8001
EOF
install -m 0644 "$PROFILE" /etc/n0jcg-winlink/radio-profile.conf
systemctl restart n0jcg-direwolf.service
systemctl restart n0jcg-webmail.service
echo "PASS: packet station profile applied for ${N0JCG_PACKET_CALLSIGN}"
