#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/etc/n0jcg-winlink"
CONFIG_FILE="$CONFIG_DIR/direwolf.conf"
PROFILE_FILE="/var/lib/n0jcg-winlink-webmail/radio-profile.conf"
[[ "${EUID:-$(id -u)}" == "0" ]] || { echo "FAIL: run with sudo" >&2; exit 1; }

CALLSIGN="${N0JCG_PACKET_CALLSIGN:-N0JCG-3}"
AUDIO_DEVICE="${N0JCG_AUDIO_DEVICE:-}"
PTT_DEVICE="${N0JCG_PTT_DEVICE:-/dev/digirig-serial}"
FREQUENCY="${N0JCG_PACKET_FREQUENCY:-145.070}"
RMS_TARGET="${N0JCG_RMS_TARGET:-N0JCG-10}"
DIGIPEATER_PATH="${N0JCG_DIGIPEATER_PATH:-}"

if [[ "${1:-}" != "--noninteractive" ]]; then
    read -r -p "Packet callsign [$CALLSIGN]: " value; CALLSIGN="${value:-$CALLSIGN}"
    read -r -p "DigiRig audio device [auto-detect]: " value; AUDIO_DEVICE="${value:-$AUDIO_DEVICE}"
    read -r -p "DigiRig serial/PTT device [$PTT_DEVICE]: " value; PTT_DEVICE="${value:-$PTT_DEVICE}"
    read -r -p "Radio frequency in MHz [$FREQUENCY]: " value; FREQUENCY="${value:-$FREQUENCY}"
    read -r -p "Packet RMS gateway target [$RMS_TARGET]: " value; RMS_TARGET="${value:-$RMS_TARGET}"
    read -r -p "Optional digipeater path (blank for direct) [$DIGIPEATER_PATH]: " value; DIGIPEATER_PATH="${value:-$DIGIPEATER_PATH}"
fi

[[ "$CALLSIGN" =~ ^[A-Z0-9-]{3,15}$ ]] || { echo "FAIL: invalid packet callsign" >&2; exit 1; }
[[ -e "$PTT_DEVICE" ]] || { echo "FAIL: PTT device not found: $PTT_DEVICE" >&2; exit 1; }
[[ -z "$AUDIO_DEVICE" || "$AUDIO_DEVICE" =~ ^(plughw|hw):([A-Za-z0-9_=]+),[0-9]+$ ]] || { echo "FAIL: audio device must identify an ALSA card, for example plughw:Device,0" >&2; exit 1; }
[[ "$RMS_TARGET" =~ ^[A-Z0-9-]{3,15}$ ]] || { echo "FAIL: invalid RMS gateway target" >&2; exit 1; }
[[ -z "$DIGIPEATER_PATH" || "$DIGIPEATER_PATH" =~ ^[A-Z0-9-]{3,15}(,[A-Z0-9-]{3,15})*$ ]] || { echo "FAIL: invalid digipeater path" >&2; exit 1; }

install -d -m 0755 "$CONFIG_DIR"
install -d -m 0750 -o "${N0JCG_APP_USER:-pi}" -g "${N0JCG_APP_USER:-pi}" "$(dirname "$PROFILE_FILE")"
cat > "$CONFIG_FILE" <<EOF
# Generated by N0JCG Winlink Email Server packet radio setup
# n0jcg-direwolf.service opens the ALSA device, meters it, and pipes PCM here.
ADEVICE stdin
CHANNEL 0
MYCALL $CALLSIGN
MODEM 1200
# The configured RMS target is known to operate in AX.25 v2.0 mode. Start
# with SABM instead of spending retry time on an unsupported SABME exchange.
V20 $RMS_TARGET
PTT $PTT_DEVICE RTS
AGWPORT 8000
KISSPORT 8001
EOF
cat > "$PROFILE_FILE" <<EOF
N0JCG_PACKET_CALLSIGN=$CALLSIGN
N0JCG_PACKET_FREQUENCY=$FREQUENCY
N0JCG_RMS_TARGET=$RMS_TARGET
N0JCG_DIGIPEATER_PATH=$DIGIPEATER_PATH
N0JCG_AUDIO_DEVICE=$AUDIO_DEVICE
N0JCG_PTT_DEVICE=$PTT_DEVICE
N0JCG_PACKET_MODE=1200-AFSK
N0JCG_PAT_CONNECT_URL=ax25+agwpe:///${DIGIPEATER_PATH:+$DIGIPEATER_PATH/}$RMS_TARGET
EOF
chmod 0644 "$CONFIG_FILE" "$PROFILE_FILE"
chown "${N0JCG_APP_USER:-pi}:${N0JCG_APP_USER:-pi}" "$PROFILE_FILE"
systemctl daemon-reload
systemctl enable --now n0jcg-direwolf.service
echo "PASS: 1200-baud AFSK profile created for $CALLSIGN at $FREQUENCY MHz"
echo "PASS: Dire Wolf restarted with the new packet configuration"
