#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/etc/n0jcg-winlink"
CONFIG_FILE="$CONFIG_DIR/direwolf.conf"
PROFILE_FILE="$CONFIG_DIR/radio-profile.conf"
[[ "${EUID:-$(id -u)}" == "0" ]] || { echo "FAIL: run with sudo" >&2; exit 1; }

CALLSIGN="${N0JCG_PACKET_CALLSIGN:-N0JCG-3}"
AUDIO_DEVICE="${N0JCG_AUDIO_DEVICE:-plughw:1,0}"
PTT_DEVICE="${N0JCG_PTT_DEVICE:-/dev/digirig-ptt}"
FREQUENCY="${N0JCG_PACKET_FREQUENCY:-145.070}"

if [[ "${1:-}" != "--noninteractive" ]]; then
    read -r -p "Packet callsign [$CALLSIGN]: " value; CALLSIGN="${value:-$CALLSIGN}"
    read -r -p "DigiRig audio device [$AUDIO_DEVICE]: " value; AUDIO_DEVICE="${value:-$AUDIO_DEVICE}"
    read -r -p "DigiRig PTT device [$PTT_DEVICE]: " value; PTT_DEVICE="${value:-$PTT_DEVICE}"
    read -r -p "Radio frequency in MHz [$FREQUENCY]: " value; FREQUENCY="${value:-$FREQUENCY}"
fi

[[ "$CALLSIGN" =~ ^[A-Z0-9-]{3,15}$ ]] || { echo "FAIL: invalid packet callsign" >&2; exit 1; }
[[ -e "$PTT_DEVICE" ]] || { echo "FAIL: PTT device not found: $PTT_DEVICE" >&2; exit 1; }
[[ "$AUDIO_DEVICE" =~ ^(plughw|hw):[0-9]+,[0-9]+$ ]] || { echo "FAIL: audio device must look like plughw:1,0" >&2; exit 1; }

install -d -m 0755 "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# Generated by N0JCG Winlink Email Server packet radio setup
ADEVICE $AUDIO_DEVICE
CHANNEL 0
MYCALL $CALLSIGN
MODEM 1200
PTT CM108 $PTT_DEVICE
AGWPORT 8000
KISSPORT 8001
EOF
cat > "$PROFILE_FILE" <<EOF
N0JCG_PACKET_CALLSIGN=$CALLSIGN
N0JCG_PACKET_FREQUENCY=$FREQUENCY
N0JCG_AUDIO_DEVICE=$AUDIO_DEVICE
N0JCG_PTT_DEVICE=$PTT_DEVICE
N0JCG_PACKET_MODE=1200-AFSK
EOF
chmod 0644 "$CONFIG_FILE" "$PROFILE_FILE"
echo "PASS: 1200-baud AFSK profile created for $CALLSIGN at $FREQUENCY MHz"
echo "INFO: receive-only validation: timeout 15s direwolf -c $CONFIG_FILE -t 0"
echo "INFO: Dire Wolf service remains inactive until receive validation is complete."
